name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # ホスト名
          username: ${{ secrets.SSH_USERNAME }} # SSH ユーザ名
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 秘密鍵の内容 -----BEGIN PRIVATE KEY-----と-----END PRIVATE KEY-----含める。cat id_rsa_~.pub >> authorized_keys設定も忘れずに
          port: ${{ secrets.SSH_PORT }} # ポート番号
          script: |
            cd ${{ secrets.PROJECT_DIRECTORY }}
            chmod +x mvnw
            git switch ${{ secrets.PRODUCTION_BRANCH }}
            git pull
            kill $(lsof -ti:${{ secrets.APPLICATION_PORT }})
            sleep 10;mvn -B clean
            ./mvnw -B package
            (nohup java -jar target/${{ secrets.JAR_FILE_NAME }} > /dev/null 2>&1 &)