name: Deploy Server

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # ホスト名
          username: ${{ secrets.SSH_USERNAME }} # SSH ユーザ名
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 秘密鍵の内容
          port: ${{ secrets.SSH_PORT }} # ポート番号
          script: |
            cd videoConverterClient
            chmod +x mvnw
            git switch master
            git pull
            kill $(ps -ef | grep '[j]ava -jar spring_jms_client-0.0.1-SNAPSHOT.jar' | awk '{print $2}')
            ./mvnw -B package
            java -jar target/*-runner.jar